version: '3.3'

networks:
  edge:
    external: true

services:
  app:
    image: ghcr.io/livck/livck-help:latest
    networks:
      edge:
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.livck-help.entrypoints=https"
        - "traefik.http.routers.livck-help.service=livck-help"
        - "traefik.http.routers.livck-help.rule=Host(`help.livck.com`)"
        - "traefik.http.routers.livck-help.tls=true"
        - "traefik.http.services.livck-help.loadbalancer.server.port=80"
        - "traefik.docker.network=edge"
